CREATE TABLE recepcion_solicitud_espera (
    id BIGINT NOT NULL AUTO_INCREMENT,
    empresa_id BIGINT NOT NULL,
    sucursal_id BIGINT NOT NULL,
    servicio_id BIGINT NOT NULL,
    cliente_id BIGINT NULL,
    cita_id BIGINT NULL,
    nombre_cliente VARCHAR(150) NOT NULL,
    telefono_cliente VARCHAR(30) NOT NULL,
    fecha_deseada DATE NOT NULL,
    hora_desde TIME NULL,
    hora_hasta TIME NULL,
    acepta_whatsapp BIT(1) NOT NULL DEFAULT b'0',
    canal_origen VARCHAR(30) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    notas VARCHAR(500) NULL,
    creado_por_usuario_id BIGINT NULL,
    creada_en DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    notificada_en DATETIME(6) NULL,
    cerrado_en DATETIME(6) NULL,
    CONSTRAINT pk_recepcion_solicitud_espera PRIMARY KEY (id),
    INDEX idx_recepcion_espera_empresa_fecha (empresa_id, fecha_deseada),
    INDEX idx_recepcion_espera_empresa_estado (empresa_id, estado),
    INDEX idx_recepcion_espera_sucursal (sucursal_id)
);
