CREATE TABLE invitacion_usuario_empresa (
    id BIGINT NOT NULL AUTO_INCREMENT,
    empresa_id BIGINT NOT NULL,
    correo VARCHAR(190) NOT NULL,
    nombre_completo VARCHAR(150) NOT NULL,
    telefono VARCHAR(30) NULL,
    puesto VARCHAR(80) NULL,
    rol_empresa_id BIGINT NULL,
    sucursal_id BIGINT NULL,
    sucursal_ids_json JSON NULL,
    permisos_directos_json JSON NULL,
    notas VARCHAR(500) NULL,
    token_hash CHAR(64) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    expira_en DATETIME(6) NOT NULL,
    aceptada_en DATETIME(6) NULL,
    cancelada_en DATETIME(6) NULL,
    creada_por_usuario_id BIGINT NOT NULL,
    creado_en DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    actualizado_en DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_invitacion_usuario_token_hash (token_hash),
    KEY idx_invitacion_empresa_correo_estado (empresa_id, correo, estado),
    CONSTRAINT fk_invitacion_usuario_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id),
    CONSTRAINT fk_invitacion_usuario_actor FOREIGN KEY (creada_por_usuario_id) REFERENCES usuario(id)
);
