logging:
  level:
    root: WARN

aplicacion:
  whatsapp:
    validar-firma-webhook: ${TWILIO_VALIDAR_FIRMA_WEBHOOK:true}

management:
  health:
    mail:
      enabled: false

spring:
  jpa:
    hibernate:
      ddl-auto: validate

server:
  forward-headers-strategy: framework
